name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Generate the DB file
        run: deno run --allow-read --allow-write db.ts

      - name: Tansfer output db file to web branch
        run: mv ./bible.db /tmp/bible.db && git checkout web && mv /tmp/bible.db ./bible.db

      - name: Depoly to Vercel
      - uses: amondnet/vercel-action@v20
        with:
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: '--prod'
