name: CI

on:
  push:
    branches: [ main, web ]
  pull_request:
    branches: [ main, web ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Generate the DB file
        run: deno run --allow-read --allow-write db.ts

      - name: Tansfer output db file to web branch
        run: |
          mv ./bible.db /tmp/bible.db
          git checkout web
          mv /tmp/bible.db ./bible.db

      - name: Commit db file for depolyment stage
      - run: |
          git config --global user.name 'Sh-Zh-7'
          git config --global user.email 'zhihaoshen7@qq.com'
          git add -A
          git commit -m "feat: update db file"
          git push

      - name: Depoly to Vercel by web hook
      - run: curl -X ${{ secrets.WEB_HOOK }}
